name: Linter

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  golangci:
    uses: TykTechnologies/github-actions/.github/workflows/golangci.yaml@main
    with:
      main_branch: "master"
  sonarcloud:
    if: ${{ always() }}
    needs: golangci
    uses: TykTechnologies/github-actions/.github/workflows/sonarcloud.yaml@main
    with:
      exclusions: ""
    secrets:
      GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
